#!/bin/bash
# Get the first sample
cpu1=$(grep 'cpu ' /proc/stat)
idle1=$(echo $cpu1 | awk '{print $5}')
total1=$(echo $cpu1 | awk '{print $2+$3+$4+$5+$6+$7+$8}')

# Wait for a second
sleep 1

# Get the second sample
cpu2=$(grep 'cpu ' /proc/stat)
idle2=$(echo $cpu2 | awk '{print $5}')
total2=$(echo $cpu2 | awk '{print $2+$3+$4+$5+$6+$7+$8}')

# Calculate the difference
idle_diff=$((idle2 - idle1))
total_diff=$((total2 - total1))

# Calculate the CPU usage percentage
cpu_usage=$((100 * (total_diff - idle_diff) / total_diff))

  printf "^c$black^ ^b$yellow^  "
  printf "^c$white^ ^b$grey^ $cpu_usage"
